import Ldde

l = Ldde.Ldde()

l.inserir_inicio('B')
l.inserir_inicio('A')
l.inserir_fim('C')
l.inserir_fim('D')
l.inserir_fim('E')
print('Ver tamanho:', l.ver_quantidade())
l.show()
print()
print('testando o remover Depois A:')
l.remover_depois('A')
l.show()
print('Ver tamanho:', l.ver_quantidade())
print('ver o primeiro:',l.ver_primeiro(), 'Ver o último:', l.ver_ultimo())
print()
print('inserindo mais elementos na lista:')
l.inserir_fim('B')
l.inserir_fim('C')
l.inserir_fim('D')
l.inserir_fim('E')
l.show()
print()
print('testando o remover Depois C:')
l.remover_depois('C')
l.show()
print('Ver tamanho:', l.ver_quantidade())
print('ver o primeiro:',l.ver_primeiro(), 'Ver o último:', l.ver_ultimo())