import Ldse

l = Ldse.Ldse()

l.inserir_inicio('A')
print('Lista após inserir inicio (A): A ')
l.show()
l.inserir_inicio('B')
print('Lista após inserir inicio (B): B A')
l.show()
l.inserir_inicio('C')
print('Lista após inserir inicio (C): C B A ')
l.show()
l.remover_inicio()
print('Lista após remover início: B A ')
l.show()
l.inserir_inicio('D')
print('Lista após inserir inicio (D): D B A ')
l.show()
l.inserir_inicio('C')
print('Lista após inserir inicio (C): C D B A ')
l.show()
l.inserir_fim('T')
print('Lista após inserir fim (T): C D B A T')
l.show()
l.remover_depois('C')
l.show()
print('Ver tamanho:', l.ver_quantidade())