import Ldse

l = Ldse.Ldse()

l.inserir_inicio('A')
print('Lista após inserir inicio (A): A ')
l.show()
l.inserir_inicio('B')
print('Lista após inserir inicio (B): B A')
l.show()
l.inserir_inicio('C')
print('Lista após inserir inicio (C): C B A ')
l.show()
l.remover_inicio()
print('Lista após remover início: B A ')
l.show()
l.inserir_inicio('D')
print('Lista após inserir inicio (D): D B A ')
l.show()
l.inserir_inicio('D')
print('Lista após inserir inicio (D): D D B A ')
l.show()
l.remover('D')
print('Lista após inserir remover (D): D B A ')
l.show()